
services:
  postgres:
    image: postgres:14
    container_name: cms_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cms
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: cms_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db

volumes:
  pgdata:
  mongodb:
